cxx_compiler_version:          # [osx]
  # need newer compiler than default for osx-arm
  - 12                         # [osx]

c_compiler:                    # [win]
- vs2019                       # [win]
cxx_compiler:                  # [win]
- vs2019                       # [win]
